### ISSUE TITLE
no such table: main.shuup_contact__old

### ISSUE THREAD

**Issue by yriahi** [shuup/shuup-project-template#5]
When I run `python manage.py shuup_init`, I get the following error:

```
Creating shop... Traceback (most recent call last):
  File "/Users/yriahi/Development/shuup2/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/yriahi/Development/shuup2/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.shuup_contact__old
...
```
It does not seem to find `main.shuup_contact__old`

**Comment by chessbr** [comment]
Hi @yriahi 
Take a look here for the issue: https://github.com/shuup/shuup/issues/1730
Just make sure to downgrade your SQLite version as it is related to Django
