### ISSUE TITLE
AttributeError: type object 'Supplier' has no attribute '_parler_meta'

### ISSUE THREAD

**Issue by oiclid** [shuup/shuup-project-template#7]
On running `python manage.py migrate` I get the following error message

`Operations to perform:
  Apply all migrations: admin, auth, campaigns, carousel, contenttypes, default_tax, discounts, easy_thumbnails, filer, registration, reversion, sessions, shuup, shuup_admin, shuup_customer_group_pricing, shuup_front, shuup_gdpr, shuup_notify, shuup_simple_cms, shuup_stripe, shuup_tasks, shuup_testing, shuup_xtheme, simple_supplier
Running migrations:
  Applying campaigns.0017_auto_20190927_0807... OK
  Applying carousel.0005_auto_20190927_0807... OK
  Applying shuup.0061_auto_20190927_0807...Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\operations\fields.py", line 211, in state_forwards
    state.reload_model(app_label, self.model_name_lower, delay=delay)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\state.py", line 166, in reload_model
    self._reload(related_models)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\state.py", line 199, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\state.py", line 323, in render_multiple
    model.render(self)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\state.py", line 626, in render
    body,
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\models\base.py", line 319, in __new__
    new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\migrations\state.py", line 356, in register_model
    self.do_pending_operations(model)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\apps\registry.py", line 422, in do_pending_operations
    function(model)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\apps\registry.py", line 401, in apply_next_model
    self.lazy_model_operation(next_function, *more_models)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\apps\registry.py", line 413, in lazy_model_operation
    apply_next_model(model_class)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\apps\registry.py", line 401, in apply_next_model
    self.lazy_model_operation(next_function, *more_models)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\apps\registry.py", line 387, in lazy_model_operation
    function()
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\models\fields\related.py", line 347, in resolve_related_class
    field.do_related_class(related, model)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\django\db\models\fields\related.py", line 408, in do_related_class
    self.contribute_to_related_class(other, self.remote_field)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\parler\fields.py", line 58, in contribute_to_related_class
    _validate_master(self.model)
  File "c:\code\shuup_test\shuup_proj\lib\site-packages\parler\fields.py", line 40, in _validate_master
    meta = shared_model._parler_meta
AttributeError: type object 'Supplier' has no attribute '_parler_meta'
`

**Comment by maximlion** [comment]
Hi @oiclid, what version of Python are you using & what database?
