### ISSUE TITLE
Requirement `shuup-yaml` fails with 404 Not Found

### ISSUE THREAD

**Issue by hielsnoppe** [shuup/shuup-project-template#8]
Running `pip install -r requirements.txt` fails with:

    Collecting shuup-yaml==1.0.1b2 (from -r requirements.txt (line 73))
    Exception:
    Traceback (most recent call last):
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
        wb.build(autobuilding=True)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
        self.requirement_set.prepare_files(self.finder)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
        ignore_dependencies=self.ignore_dependencies))
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
        require_hashes
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
        self.link = finder.find_requirement(self, upgrade)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
        all_candidates = self.find_all_candidates(req.name)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
        for page in self._get_pages(url_locations, project_name):
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
        page = self._get_page(location)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
        return HTMLPage.get_page(link, session=self.session)
      File "/home/niels/Projects/dd24/shuup/.venv/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
        resp.raise_for_status()
      File "/home/niels/Projects/dd24/shuup/.venv/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/shuup-yaml/

**Comment by hielsnoppe** [comment]
Workaround: Install from GitHub by replacing in `requirements.txt`:

    #shuup-yaml==1.0.1b2
    git+https://github.com/shuup/shuup-yaml.git@v1.0.1b2

**Comment by franckbret** [comment]
A wheel is included https://github.com/shuup/shuup-project-template/tree/master/wheels , so install wheel and it will run fine.

```
pip install -U pip
pip install -U setuptools
pip install -U wheel
pip install -r requirements.txt
```
